language: cpp
git:
  depth: 50
  submodules: true
exclude:
    - if: branch = continous
jobs:
  include:
  - stage: build
    name: Build for Win32 x86 MSVC/CMake
    cache: ccache
    os: windows
    language: cpp
    script:
    - mkdir -p win-build && cd win-build
    - cmake -G "Visual Studio 15 2017" -A Win32 -DCMAKE_BUILD_TYPE=Release ../
    - cmake --build . --config Release
    - cd ..
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "CSMoE-Deployer"
      - git config --local user.email "824395314@qq.com"
      - export TRAVIS_TAG=continuous
      - git remote add travis-deploy-public https://${GITHUB_TOKEN}@github.com/MoeMod/z4d.git
      - git tag --delete ${TRAVIS_TAG} || echo "tag not exists..."
      - git push travis-deploy-public --delete ${TRAVIS_TAG} || echo "remote tag not exists..."
      - git tag --force ${TRAVIS_TAG}
      - git push travis-deploy-public --tags --force
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file:
        - win-build/src/Release/z4d.csgo.ext.dll
      on:
        branch: master
        repo: MoeMod/z4d
      overwrite: true
      skip_cleanup: true
      prerelease: true
