language: cpp
git:
  depth: 50
  submodules: true
jobs:
  include:
  - stage: build
    name: Build for Win32 x86 MSVC/CMake
    cache: ccache
    os: windows
    language: cpp
    script:
    - mkdir -p win-build && cd win-build
    - cmake -G "Visual Studio 15 2017" -A Win32 -DCMAKE_BUILD_TYPE=Release ../
    - cmake --build . --config Release
    - cd ..
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file:
        - win-build/src/z4d.csgo.ext.dll
      on:
        branch: master
        repo: MoeMod/z4d
      overwrite: true
      skip_cleanup: true
      prerelease: true
